ci:
    autofix_commit_msg: 'ci: auto fixes from pre-commit hooks'
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
